<?php
return array(
	'tagline' => 'The Easiest Way To Document Your Project',
	'theme' => 'navy',
	'image' => 'img/app.png',
	'docs_url' => 'default',//the first post of documentation, if default it will use the first post that you created
	'right_nav_link' => 'Generated by <a href="http://daux.io">Daux.io</a>',
	'float' => true,
	'date_modified' => true,
	'repo' => 'justinwalsh/daux.io',
	'twitter' => array( 'imknight' ),
	'google_analytics' => false,
	'piwik_analytics' => false,
	'links' =>array(
		'Link 1' => '',
		'Link 2' => '',
		'Link 3' => '',
	),
);
